### ISSUE TITLE
Enrich content in HTML fields so that links are displayed properly.

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/rol#2]
In getData for Actors and Items, it would be nice to have `TextEditor.enrichHTML` used to enrich the HTML content before it gets displayed in Actor/Item sheets.

This will convert links such as `@UUID` into the correct HTML so that the link is displayed to the user.

**Comment by Genii-Locorum** [comment]
I've added this to the project plan - will aim to sort it whilst I do ugrades to Foundry V12 (might take a week or two).

Are there any specific areas you're looking at (such as descriptions etc)?  It's been a while since I looked at RoL 

Thanks for calling these out - nice to know someone is reviewing/using i

Cheers

Simon

**Comment by farling42** [comment]
In Items, the Description field.

In "character" Actors, the three fields in the Biography tab (Present, First Supernatural Encounter, Childhood), and the Description field of Items, and the Development Point Spend History (I imagine putting links to the things that have been purchased).

In "npc" Actors, the Description and Notes fields.

If/when you convert to use DataFields, it might be easier to spot the fields which are of type HTMLField, which could benefit from enriching.

**Comment by farling42** [comment]
Yes, looking good :-)

**Comment by farling42** [comment]
If you drag an item into that field, it should add the text `@UUID...` which you see in the editor, but when the editor is closed then a clickable link should be displayed.

**Comment by Genii-Locorum** [comment]
Yep, it does that.  I will close this issue when I release the update (unless there's other stuff to call out

![image](https://github.com/Genii-Locorum/rol/assets/121451824/dd99505c-3987-4bf8-b19d-6c3374407d35)

**Comment by farling42** [comment]
Yes, that is the presentation that was missing :-)

**Comment by Genii-Locorum** [comment]
Adjustments made in release 13
