### ISSUE TITLE
Version 12.1.13 generates an error on Foundry V11

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/rol#4]
The following error occurs when starting ROL on Foundry V11.

![image](https://github.com/Genii-Locorum/rol/assets/17485384/3b4ce985-77e9-4242-b4af-4b9d99029f54)

It is failing to find the class `foundry.dice.terms.DiceTerm`

**Comment by Genii-Locorum** [comment]
Thanks, my bad - I should have moved the minimum version to 12 rather than 11.  I will correct and re-release.

**Comment by Genii-Locorum** [comment]
Updated the release.
