### ISSUE TITLE
Manifest links on foundry page have wrong github project

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/rol#5]
The links on the package manifest page at https://foundryvtt.com/packages/rol are showing "Rivers-of-London" as the github project, rather than "rol", so no manifest links install.

**Comment by Genii-Locorum** [comment]
Thank you - I'm trying to juggle way too many things tonight.  Updated

**Comment by farling42** [comment]
Finally, the download line in the system.json is wrongly pointed to the latest download rather than the specific system.zip for the release referenced by the system.json

**Comment by Genii-Locorum** [comment]
Cheers - right, let me look in to changing the released versions

________________________________
